import { Wrench } from 'lucide-react'
import { cn } from '@/lib/utils'

interface SystemGeneratedBadgeProps {
  size?: 'xs' | 'sm' | 'md'
  compact?: boolean
}

/** Badge for documents generated by automated system processes. */
export function SystemGeneratedBadge({ size = 'sm', compact }: SystemGeneratedBadgeProps) {
  const label = compact || size === 'xs' ? 'System' : 'System Generated'

  return (
    <span
      aria-label="System generated document"
      className={cn(
        'inline-flex max-w-[140px] items-center gap-1 rounded-full bg-[#E0F2FE] font-semibold leading-none text-[#0369A1] whitespace-nowrap',
        size === 'xs' && 'h-5 px-1.5 text-[10px]',
        size === 'sm' && 'h-[22px] px-2 text-[11px]',
        size === 'md' && 'h-[26px] px-2.5 text-[12px]',
      )}
    >
      <Wrench className={cn('shrink-0', size === 'xs' ? 'h-3 w-3' : 'h-3.5 w-3.5')} />
      <span className="truncate">{label}</span>
    </span>
  )
}
